import { Link } from 'react-router';
import { StickFigure } from '../components/StickFigure';
import { KB_STATS } from '../data/knowledge';

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="border border-black/10 bg-white p-6"><h2 className="text-2xl font-[Playfair_Display]">{title}</h2><div className="mt-3 space-y-3 font-[Inter] text-black/70">{children}</div></section>;

export function HowItWorksPage() {
  return <div className="min-h-screen bg-[#f9f8f7] p-4 md:p-8"><div className="mx-auto max-w-4xl"><header className="mb-8 flex items-center gap-4 border-y-4 border-double border-black py-6"><StickFigure pose="thinking" size={84}/><div><div className="font-[JetBrains_Mono] text-xs uppercase tracking-widest text-black/50">CareerCase · responsible guidance</div><h1 className="text-4xl font-[Playfair_Display]">How the map works</h1><p className="mt-2 font-[Inter] text-black/55">Transparent signals, calibrated language, and your agency at every turn.</p></div></header><div className="space-y-5">
    <Section title="Scoring is deterministic"><p>Eleven components—interests, aptitude, values, skills, transferable evidence, experience, aspirations, market signal, progression, learning feasibility and geography—are calculated in TypeScript over a versioned knowledge base. Segment weights sum to 100%; no language model supplies a score.</p><div className="border-l-4 border-black bg-[#f9f8f7] p-4"><div className="font-[JetBrains_Mono] text-xs uppercase">Worked example</div><p className="mt-2">For a career switcher, transferable fit carries 22%. A transferable score of 80 contributes 17.6 points: <span className="font-[JetBrains_Mono]">80 × 0.22</span>. Every other available component is calculated the same way and the weighted contributions form the displayed composite. “Why this?” exposes the exact bars and missing-data notes.</p></div></Section>
    <Section title="Skills, gaps and pathways"><p>Skill fit compares current proficiency with the required level, weighted by importance. Missing evidence lowers confidence rather than pretending certainty. The Skill Gap Index is proficiency- and confidence-adjusted; readiness is <span className="font-[JetBrains_Mono]">100 − SGI</span>. Routes use curated transition edges and NSQF-aligned qualifications.</p><p className="font-[JetBrains_Mono] text-xs">Current release · {KB_STATS.occupations} occupations · {KB_STATS.skills} skills · {KB_STATS.transitions} transitions · {KB_STATS.qualifications} learning routes</p></Section>
    <Section title="What the LLM does—and does not do"><p>It can help converse, extract literal resume evidence, structure aspirations, translate, and polish wording. It does not decide scores, gaps, requirements, demand signals or routes. If the AI proxy is unavailable, onboarding, assessments, matching and pathway planning still work; only those optional language services degrade.</p></Section>
    <Section title="Fairness and limits"><p>Names and gender are never engine inputs; a repeatable six-persona developer check verifies equal outputs when only names and locations vary. Historical transition prevalence is one signal, never destiny. <strong>This transition is less common historically, but the evidence does not justify excluding it.</strong></p><p>The aptitude module is a 5-minute screener, not a clinical battery. Recommendations are strong options to explore—not predictions, diagnoses or guarantees. Demand is a curated indicative snapshot labelled by period and region.</p></Section>
    <Section title="Privacy and data rights"><p>Career Passport processing is consent-led. Users under 18 follow a guardian-confirmation demo flow aligned to DPDP Act 2023 §9; production verification should use DigiLocker or an equivalent verified channel. Settings lets you inspect raw data, export the full guidance record, review consent history, or delete guidance data while retaining the account.</p></Section>
    <Section title="Grounding and sources"><p>Occupation identifiers and role structure are grounded in NCO-2015; levels and learning routes use NSQF/NQR concepts, including multiple entry and exit language inspired by the NCrF. Market signals are curated, indicative snapshots—not live government statistics.</p><p className="text-sm">Sources note: NCO-2015 · NSQF · National Qualifications Register · curated indicative market data.</p></Section>
  </div><div className="mt-8 flex flex-wrap gap-3"><Link to="/passport" className="min-h-11 border border-black/20 px-5 py-3 font-[Inter]">Inspect my passport</Link><Link to="/recommendations" className="min-h-11 bg-black px-5 py-3 font-[Inter] text-white">Open my landscape</Link></div></div></div>;
}
export default HowItWorksPage;
