import { Link } from 'react-router';
import { Route, ArrowRight, ClipboardCheck } from 'lucide-react';
import { useGuidance } from '../context/GuidanceContext';
import { occupationById } from '../data/knowledge';
import { GuidanceEntrance } from '../components/guidance/GuidanceEntrance';
import { useT } from '../i18n';

const copy = {
  en: { startTitle: 'Your pathways start with you.', startBody: 'Build your profile first, then we’ll turn your matches into practical routes.', start: 'Start profile', eyebrow: 'CareerCase · action desk', title: 'Your pathways', intro: 'Turn your strongest matches into a route with concrete milestones. Mark steps done as you make progress.', route: 'Route', readiness: 'readiness', done: 'steps done', open: 'Open route →', next: 'Recommended next routes', all: 'See all matches', build: 'Build pathway →', emptyTitle: 'Choose a match to build your first route.', emptyBody: 'Your recommendations become step-by-step pathways once you open one.' },
  hi: { startTitle: 'आपके मार्ग आपसे शुरू होते हैं।', startBody: 'पहले अपनी प्रोफ़ाइल बनाएँ, फिर हम आपके मेलों को व्यावहारिक मार्गों में बदलेंगे।', start: 'प्रोफ़ाइल शुरू करें', eyebrow: 'CareerCase · कार्य डेस्क', title: 'आपके मार्ग', intro: 'अपने मजबूत करियर मेल को स्पष्ट चरणों वाले मार्ग में बदलें। आगे बढ़ते समय चरण पूरे करें।', route: 'मार्ग', readiness: 'तैयारी', done: 'चरण पूर्ण', open: 'मार्ग खोलें →', next: 'अगले सुझाए गए मार्ग', all: 'सभी मेल देखें', build: 'मार्ग बनाएँ →', emptyTitle: 'अपना पहला मार्ग बनाने के लिए एक करियर मेल चुनें।', emptyBody: 'किसी सुझाव को खोलते ही वह चरण-दर-चरण मार्ग बन जाएगा।' },
  te: { startTitle: 'మీ మార్గాలు మీతోనే మొదలవుతాయి.', startBody: 'ముందుగా మీ ప్రొఫైల్ నిర్మించండి; ఆపై మీ మ్యాచ్‌లను ఆచరణాత్మక మార్గాలుగా మారుస్తాము.', start: 'ప్రొఫైల్ ప్రారంభించండి', eyebrow: 'CareerCase · కార్యాచరణ డెస్క్', title: 'మీ మార్గాలు', intro: 'మీ బలమైన కెరీర్ మ్యాచ్‌లను స్పష్టమైన మైలురాళ్లతో మార్గంగా మార్చండి. పురోగతి సాధించినప్పుడు దశలను పూర్తి చేయండి.', route: 'మార్గం', readiness: 'సిద్ధత', done: 'దశలు పూర్తయ్యాయి', open: 'మార్గం తెరవండి →', next: 'తదుపరి సూచించిన మార్గాలు', all: 'అన్ని మ్యాచ్‌లు చూడండి', build: 'మార్గం రూపొందించండి →', emptyTitle: 'మీ మొదటి మార్గాన్ని నిర్మించడానికి ఒక కెరీర్ మ్యాచ్‌ను ఎంచుకోండి.', emptyBody: 'మీరు ఒక సూచనను తెరిచిన వెంటనే అది దశలవారీ మార్గంగా మారుతుంది.' },
} as const;

export function PathwaysPage() {
  const { lang } = useT();
  const c = copy[lang];
  const { passport, pathways, recommendations } = useGuidance();
  if (!passport) return <div className="min-h-screen bg-[var(--paper)] px-6 py-24 text-center"><h1 className="font-display text-4xl">{c.startTitle}</h1><p className="mx-auto mt-4 max-w-lg text-[var(--ink-soft)]">{c.startBody}</p><Link to="/onboarding" className="mt-7 inline-flex min-h-11 items-center gap-2 bg-[var(--ink)] px-5 py-3 font-mono-ui text-xs uppercase text-[var(--paper)]">{c.start} <ArrowRight size={15}/></Link></div>;
  const active = pathways.filter(plan => plan.chosenRoute);
  return <div className="min-h-screen bg-[var(--paper)] px-6 py-16 pb-28 md:py-24"><GuidanceEntrance className="mx-auto max-w-5xl"><header className="mb-12 border-b-2 border-[var(--ink)] pb-8"><div className="label-caps">{c.eyebrow}</div><h1 className="font-display mt-3 text-5xl tracking-tight md:text-6xl">{c.title}</h1><p className="mt-4 max-w-2xl text-[var(--ink-soft)]">{c.intro}</p></header>{active.length ? <section className="grid gap-4 md:grid-cols-2">{active.map(plan => { const occupation = occupationById.get(plan.occupationId); const route = plan.routes.find(item => item.kind === plan.chosenRoute); const done = route?.steps.filter(step => step.done).length ?? 0; const total = route?.steps.length ?? 0; return <Link key={plan.occupationId} to={`/pathway/${plan.occupationId}`} className="group border-2 border-[var(--ink)] bg-[var(--paper-raised)] p-6 transition-transform hover:-translate-y-1"><Route size={20}/><h2 className="font-display mt-5 text-3xl">{occupation?.title ?? plan.occupationId}</h2><p className="mt-2 text-sm text-[var(--ink-soft)]">{route?.label ?? c.route} · {plan.gapReport.readiness}% {c.readiness}</p><div className="mt-6 h-2 bg-[var(--ink)]/15"><div className="h-full bg-[var(--ink)]" style={{ width: `${total ? done / total * 100 : 0}%` }}/></div><div className="mt-2 flex justify-between font-mono-ui text-xs uppercase"><span>{done}/{total} {c.done}</span><span className="group-hover:underline">{c.open}</span></div></Link>; })}</section> : <section className="border-2 border-dashed border-[var(--ink)]/35 bg-[var(--paper-raised)] p-8 text-center"><ClipboardCheck className="mx-auto"/><h2 className="font-display mt-4 text-3xl">{c.emptyTitle}</h2><p className="mt-3 text-[var(--ink-soft)]">{c.emptyBody}</p></section>}<section className="mt-12"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-3xl">{c.next}</h2><Link to="/recommendations" className="font-mono-ui text-xs uppercase underline">{c.all}</Link></div><div className="grid gap-3 md:grid-cols-3">{recommendations?.recommendations.slice(0, 3).map((item, index) => { const occupation = occupationById.get(item.occupationId); return <Link key={item.occupationId} to={`/pathway/${item.occupationId}`} className="border border-[var(--ink)]/20 p-5"><span className="font-mono-ui text-xs">#{index + 1} · {item.totalScore}% match</span><h3 className="font-display mt-4 text-2xl">{occupation?.title ?? item.occupationId}</h3><span className="mt-5 inline-block text-sm underline">{c.build}</span></Link>; })}</div></section></GuidanceEntrance></div>;
}
export default PathwaysPage;
