import { occupationById, qualificationsForOccupation, qualificationsForSkill, transitionsFrom } from '../data/knowledge';
import type { CareerPassport, PathwayPlan, PathwayRoute, PathwayStep } from './types';
import { computeGapReport, skillName } from './gaps';
export function buildPathwayPlan(passport: CareerPassport, occupationId: string): PathwayPlan {
  const occupation=occupationById.get(occupationId); const gap=computeGapReport(passport,occupationId); const hours=Math.max(1,passport.constraints.weeklyLearningHours); const factor=Math.max(.6,Math.min(2,6/hours)); const quals=qualificationsForOccupation(occupationId); const topQual=quals[0]; const missing=gap.gaps.filter(g=>g.severity>0).slice(0,3);
  const learn=(qualificationId?:string):PathwayStep=>{const q=qualificationId?quals.find(x=>x.id===qualificationId):undefined;return {kind:q?'qualification':'learn',label:q?q.name:'Practice '+missing.map(g=>skillName(g.skillId)).join(', '),refId:q?.id,nsqfLevel:q?.nsqfLevel,estMonths:q?Math.max(1,Math.round(q.typicalMonths*factor)):Math.max(1,missing.length),done:false}};
  const direct:PathwayRoute={kind:'direct',label:'Fastest',tradeoff:'Fastest but self-driven',steps:[...gap.transferable.slice(0,2).map(t=>({kind:'validate_skill' as const,label:'Validate '+skillName(t.skillId),refId:t.skillId,estMonths:1,done:false})),learn(topQual?.id),{kind:'project',label:'Build a small portfolio project',estMonths:1,done:false},{kind:'target',label:'Explore '+(occupation?.title??occupationId),refId:occupationId,estMonths:0,done:false}],totalMonths:0,confidence:'medium'};
  direct.totalMonths=direct.steps.reduce((s,x)=>s+x.estMonths,0);
  const edge=passport.experiences.flatMap(e=>e.occupationId?transitionsFrom(e.occupationId):[]).find(e=>e.toId!==occupationId); const middle=edge?occupationById.get(edge.toId):undefined;
  const stepping:PathwayRoute={kind:'stepping_stone',label:'Lower-risk',tradeoff:'Slower, income continues',steps:middle?[{kind:'transition_role',label:'Move through '+middle.title,refId:middle.id,estMonths:Math.max(3,Math.round(edge!.typicalYears*9)),done:false},learn(),{kind:'target',label:'Move into '+(occupation?.title??occupationId),refId:occupationId,estMonths:0,done:false}]:[{kind:'qualification',label:'Use an apprenticeship as a stepping stone',refId:topQual?.id,estMonths:topQual?Math.max(1,Math.round(topQual.typicalMonths*factor)):3,done:false},{kind:'target',label:'Move into '+(occupation?.title??occupationId),refId:occupationId,estMonths:0,done:false}],totalMonths:0,confidence:'medium'}; stepping.totalMonths=stepping.steps.reduce((s,x)=>s+x.estMonths,0);
  const credential:PathwayRoute={kind:'qualification_first',label:'Credential route',tradeoff:'Strongest credential, highest cost',steps:[learn(topQual?.id),{kind:'project',label:'Apply the new learning in a supervised project',estMonths:1,done:false},{kind:'target',label:'Explore '+(occupation?.title??occupationId),refId:occupationId,estMonths:0,done:false}],totalMonths:0,confidence:topQual?'high':'low'}; credential.totalMonths=credential.steps.reduce((s,x)=>s+x.estMonths,0);
  return {occupationId,routes:[direct,stepping,credential],gapReport:gap,createdAt:new Date().toISOString()};
}
