import { useState } from 'react';
import { motion } from 'motion/react';
import type { PathwayRoute, PathwayStep } from '../../engine/types';
import type { Language } from '../../i18n';
import { localizedStep, localizedStepKind } from '../../i18n/guidanceFormatting';

export function PathwayGraph({ route, lang = 'en' }: { route: PathwayRoute; lang?: Language }) {
  const [selected, setSelected] = useState<PathwayStep | null>(null);
  const width = Math.max(680, route.steps.length * 180);
  const months = lang === 'hi' ? 'महीने' : lang === 'te' ? 'నెలలు' : 'months';
  const nodeNote = lang === 'hi' ? 'यह नोड ज्ञान-आधार के कौशल, योग्यता या बदलाव प्रमाण से समर्थित है। समय या धन लगाने से पहले पासपोर्ट में संबंधित प्रमाण खोलें।' : lang === 'te' ? 'ఈ నోడ్ జ్ఞాన భాండాగారంలోని నైపుణ్యం, అర్హత లేదా మార్పు ఆధారంతో మద్దతు పొందింది. సమయం లేదా డబ్బు వెచ్చించే ముందు పాస్‌పోర్ట్‌లో సంబంధిత ఆధారాన్ని తెరవండి.' : 'This node is reachable because it is backed by a knowledge-base skill, qualification, or transition edge. Open the related evidence in your passport before committing time or money.';
  return <div className="relative"><div className="overflow-x-auto border border-black/10 bg-white p-3"><svg viewBox={`0 0 ${width} 190`} className="min-w-[680px] w-full" aria-label={`${route.label} pathway graph`}><defs><marker id="path-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0l10 5-10 5z" fill="#1a1a1a"/></marker></defs>{route.steps.slice(0, -1).map((_, index) => <motion.path key={`edge-${index}`} d={`M${95 + index * 180} 91 C${130 + index * 180} ${72 + (index % 2) * 28}, ${165 + index * 180} ${112 - (index % 2) * 28}, ${196 + index * 180} 91`} fill="none" stroke="#1a1a1a" strokeWidth="2.5" strokeLinecap="round" markerEnd="url(#path-arrow)" initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:.6,delay:index*.12}}/>)}{route.steps.map((step,index) => <motion.g key={`${step.kind}-${index}`} onClick={() => setSelected(step)} role="button" tabIndex={0} className="cursor-pointer" initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.12}}><path d={`M${20 + index * 180} 55 q4 -5 10 0 h125 q6 3 2 9 v55 q2 8 -7 7 h-120 q-10 2 -10 -8z`} fill={step.done?'#1a1a1a':'#f9f8f7'} stroke="#1a1a1a" strokeWidth="2"/><text x={32 + index * 180} y="77" fontFamily="JetBrains Mono" fontSize="9" fill={step.done?'#fff':'#555'}>{localizedStepKind(step.kind,lang).toUpperCase()}</text><foreignObject x={32 + index * 180} y="84" width="112" height="32"><div className={`font-[Inter] text-[11px] leading-tight ${step.done?'text-white':'text-black'}`}>{localizedStep(step,lang)}</div></foreignObject><text x={32 + index * 180} y="117" fontFamily="JetBrains Mono" fontSize="9" fill={step.done?'#fff':'#555'}>{step.estMonths} {months.toUpperCase()}</text></motion.g>)}</svg></div>{selected && <div className="fixed inset-x-0 bottom-0 z-[65] border-t-2 border-black bg-[#f9f8f7] p-5 shadow-2xl"><div className="mx-auto max-w-3xl"><div className="flex justify-between"><div><div className="font-[JetBrains_Mono] text-[10px] uppercase tracking-widest">{localizedStepKind(selected.kind,lang)} · {selected.estMonths} {months}</div><h3 className="font-[Playfair_Display] text-2xl">{localizedStep(selected,lang)}</h3></div><button className="min-h-11 min-w-11 border border-black/20" onClick={() => setSelected(null)}>×</button></div><p className="mt-3 font-[Inter] text-sm text-black/65">{nodeNote}</p></div></div>}</div>;
}
