import { useState } from 'react';
import type { SkillClaim, SkillEvidence } from '../../engine/types';
import { skillClaimName } from '../../engine/skillProfile';

export function SkillValidationDialog({ claim, onClose, onValidate }: { claim: SkillClaim; onClose: () => void; onValidate: (evidence: SkillEvidence) => void }) {
  const [checks, setChecks] = useState([false,false,false]);
  const [credential, setCredential] = useState('');
  const passCount = checks.filter(Boolean).length;
  const skillName = skillClaimName(claim);
  return <div className="fixed inset-0 z-[70] bg-black/30 p-4 flex items-center justify-center" role="dialog" aria-modal="true"><div className="w-full max-w-lg border-2 border-black bg-[#f9f8f7] p-6"><div className="flex justify-between"><div><div className="font-[JetBrains_Mono] text-[10px] uppercase tracking-widest">Recognition of Prior Learning</div><h2 className="font-[Playfair_Display] text-3xl">Validate {skillName}</h2></div><button onClick={onClose} className="min-h-11 min-w-11 border border-black/20">×</button></div><p className="mt-4 font-[Inter] text-sm text-black/60">Use a concrete self-audit. This adds evidence; it does not issue a formal qualification.</p><div className="mt-5 space-y-3">{[`I can explain the core concepts of ${skillName}.`,`I can complete a representative task without step-by-step help.`,`I can identify and correct a common mistake in this work.`].map((label,index)=><label key={label} className="flex min-h-11 items-start gap-3 border border-black/10 bg-white p-3 font-[Inter] text-sm"><input type="checkbox" checked={checks[index]} onChange={event=>setChecks(current=>current.map((value,i)=>i===index?event.target.checked:value))}/>{label}</label>)}</div><div className="my-5 flex items-center gap-3"><div className="h-px flex-1 bg-black/10"/><span className="font-[JetBrains_Mono] text-[10px]">OR CREDENTIAL</span><div className="h-px flex-1 bg-black/10"/></div><input value={credential} onChange={event=>setCredential(event.target.value)} placeholder="Course or credential name / link" className="w-full border border-black/20 p-3 font-[Inter] text-sm"/><button disabled={!credential.trim() && passCount < 2} onClick={()=>onValidate({type:credential.trim()?'credentialed':'self_reported',description:credential.trim()?`Credential: ${credential.trim()}`:`Passed ${passCount}/3 concrete self-audit checks`,confidence:credential.trim()?.9:.75,observedAt:new Date().toISOString()})} className="mt-5 min-h-11 w-full bg-black text-white font-[Inter] disabled:opacity-30">Add validation evidence</button></div></div>;
}
