import { useState } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { KB_STATS, KB_VERSION, QUALIFICATIONS } from '../../data/knowledge';
import { useT } from '../../i18n';
import { WhyPanel, type ScoreEvidence } from './WhyPanel';

export function TrustStrip({ compact = false }: { compact?: boolean }) {
  const { lang } = useT(); const reduced = useReducedMotion(); const [why, setWhy] = useState<ScoreEvidence | null>(null);
  const c = lang === 'hi' ? { nco:'NCO-2015 आधारित', nsqf:'NSQF-संबद्ध मार्ग', dpdp:'DPDP अधिनियम 2023 सहमति', deterministic:'नियतात्मक स्कोरिंग', read:'पूरी विधि पढ़ें', title:'विश्वास प्रमाण', ncoSummary:'व्यवसाय IDs और संरचना NCO-2015 पर आधारित हैं।', nsqfSummary:'सीखने के मार्ग NSQF स्तरों और अनेक प्रवेश/निकास विकल्पों से जुड़े हैं।', dpdpSummary:'प्रसंस्करण सहमति-आधारित है; नाबालिगों के लिए अभिभावक प्रवाह लागू है।', deterministicSummary:'11 TypeScript घटक, जिनके भार 100% होते हैं, स्कोर निकालते हैं; LLM स्कोर नहीं देता।', method:'संस्करणित ज्ञान-आधार और नियम-आधारित गणना।', rights:'डेटा अधिकार', export:'सेटिंग्स में निर्यात का अधिकार', delete:'सेटिंग्स में हटाने का अधिकार', consent:'सहमति वापस लेने का अधिकार', guardian:'18 से कम आयु के लिए अभिभावक सहमति', example:'कार्य उदाहरण', counts:'ज्ञान-आधार गणना' } : lang === 'te' ? { nco:'NCO-2015 ఆధారితం', nsqf:'NSQF-సమన్వయ మార్గాలు', dpdp:'DPDP చట్టం 2023 సమ్మతి', deterministic:'నిర్ణీత స్కోరింగ్', read:'పూర్తి పద్ధతి చదవండి', title:'నమ్మక ఆధారం', ncoSummary:'వృత్తి IDలు, నిర్మాణం NCO-2015 ఆధారితం.', nsqfSummary:'అభ్యాస మార్గాలు NSQF స్థాయిలు మరియు పలు ప్రవేశ/నిష్క్రమణలతో ఉంటాయి.', dpdpSummary:'ప్రాసెసింగ్ సమ్మతి ఆధారితం; మైనర్లకు సంరక్షక ప్రవాహం వర్తిస్తుంది.', deterministicSummary:'100%కు కలిసే 11 TypeScript భాగాలు స్కోర్లు లెక్కిస్తాయి; LLM స్కోర్ ఇవ్వదు.', method:'వెర్షన్ చేసిన జ్ఞాన భాండాగారం, నియమ-ఆధారిత లెక్కింపు.', rights:'డేటా హక్కులు', export:'సెట్టింగ్స్‌లో ఎగుమతి హక్కు', delete:'సెట్టింగ్స్‌లో తొలగింపు హక్కు', consent:'సమ్మతి ఉపసంహరణ హక్కు', guardian:'18 కంటే తక్కువ వారికి సంరక్షక సమ్మతి', example:'పని చేసిన ఉదాహరణ', counts:'జ్ఞాన భాండాగార లెక్కలు' } : { nco:'NCO-2015 GROUNDED', nsqf:'NSQF-ALIGNED ROUTES', dpdp:'DPDP ACT 2023 CONSENT', deterministic:'DETERMINISTIC SCORING', read:'Read the full method', title:'Trust evidence', ncoSummary:'Occupation IDs and structure are grounded in NCO-2015.', nsqfSummary:'Learning routes carry NSQF levels and support multiple entry and exit points.', dpdpSummary:'Processing is consent-led, with a guardian flow for under-18s.', deterministicSummary:'11 TypeScript components with weights totaling 100% calculate scores; LLM never supplies one.', method:'Versioned knowledge base and rule-based computation.', rights:'Data rights', export:'Export right in Settings', delete:'Delete right in Settings', consent:'Right to withdraw consent', guardian:'Guardian consent for under-18s', example:'Worked example', counts:'Knowledge-base counts' };
  const counts = Object.entries(QUALIFICATIONS.reduce<Record<string, number>>((a, q) => ({ ...a, [q.type]: (a[q.type] ?? 0) + 1 }), {}));
  const evidence = (kind: string): ScoreEvidence => kind === 'nco' ? { title:c.title, eyebrow:c.nco, summary:c.ncoSummary, method:c.method, items:[{label:c.counts,detail:`${KB_STATS.occupations} occupations · ${KB_STATS.skills} skills · ${KB_STATS.transitions} transitions · ${KB_STATS.qualifications} qualifications`}], source:'NCO-2015 · NSQF · NQR', footerLink:{to:'/how-it-works',label:c.read} } : kind === 'nsqf' ? { title:c.title, eyebrow:c.nsqf, summary:c.nsqfSummary, method:c.method, items:counts.map(([type,count])=>({label:type,detail:`${count} routes`})), source:'NSQF · NCrF', footerLink:{to:'/how-it-works',label:c.read} } : kind === 'dpdp' ? { title:c.title, eyebrow:c.dpdp, summary:c.dpdpSummary, method:c.method, items:[c.export,c.delete,c.consent,c.guardian].map(detail=>({label:c.rights,detail})), source:'DPDP Act 2023 §9', footerLink:{to:'/how-it-works',label:c.read} } : { title:c.title, eyebrow:c.deterministic, summary:c.deterministicSummary, method:c.method, items:[{label:c.example,detail:'80 × 0.22 = 17.6'},{label:'LLM',detail:'LLM not used for this score.'}], source:`Deterministic engine · ${KB_VERSION}`, footerLink:{to:'/how-it-works',label:c.read} };
  const badges = [['nco',c.nco],['nsqf',c.nsqf],['dpdp',c.dpdp],['deterministic',c.deterministic]] as const;
  return <section className="my-6" aria-label={c.title}><div className="flex flex-wrap gap-2">{badges.map(([id,label],index)=><motion.button key={id} data-testid={`trust-badge-${id}`} onClick={()=>setWhy(evidence(id))} className="min-h-11 border border-[var(--ink)] px-3 font-mono-ui text-[10px] uppercase tracking-widest" initial={reduced?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:reduced?0:index*.05}}>{label}</motion.button>)}</div>{!compact&&<p className="mt-2 font-mono-ui text-[10px] uppercase text-[var(--ink-soft)]">KB v{KB_VERSION} · {KB_STATS.occupations} occupations · {KB_STATS.skills} skills</p>}{why&&<WhyPanel evidence={why} onClose={()=>setWhy(null)}/>}</section>;
}
