import type { Language } from './index';

type Names = { hi: string; te: string };

// Curated display names for every occupation in KB kb-2026.06.1.
const names: Record<string, Names> = {
  'software-developer':{hi:'सॉफ़्टवेयर डेवलपर',te:'సాఫ్ట్‌వేర్ డెవలపర్'}, 'data-analyst':{hi:'डेटा विश्लेषक',te:'డేటా విశ్లేషకుడు'}, 'cybersecurity-analyst':{hi:'साइबर सुरक्षा विश्लेषक',te:'సైబర్ భద్రత విశ్లేషకుడు'}, 'web-developer':{hi:'वेब डेवलपर',te:'వెబ్ డెవలపర్'}, 'mobile-app-developer':{hi:'मोबाइल ऐप डेवलपर',te:'మొబైల్ యాప్ డెవలపర్'},
  'data-scientist':{hi:'डेटा वैज्ञानिक',te:'డేటా శాస్త్రవేత్త'}, 'network-administrator':{hi:'नेटवर्क प्रशासक',te:'నెట్‌వర్క్ నిర్వాహకుడు'}, 'database-administrator':{hi:'डेटाबेस प्रशासक',te:'డేటాబేస్ నిర్వాహకుడు'}, 'it-support-specialist':{hi:'आईटी सहायता विशेषज्ञ',te:'ఐటీ సహాయ నిపుణుడు'}, 'devops-engineer':{hi:'डेवऑप्स इंजीनियर',te:'డెవ్‌ఆప్స్ ఇంజనీర్'}, 'ui-ux-designer':{hi:'यूआई/यूएक्स डिज़ाइनर',te:'యూఐ/యూఎక్స్ డిజైనర్'},
  doctor:{hi:'चिकित्सक',te:'వైద్యుడు'}, nurse:{hi:'नर्सिंग पेशेवर',te:'నర్సింగ్ నిపుణుడు'}, 'lab-technician':{hi:'चिकित्सा प्रयोगशाला तकनीशियन',te:'వైద్య ప్రయోగశాల సాంకేతిక నిపుణుడు'}, pharmacist:{hi:'फार्मासिस्ट',te:'ఫార్మసిస్ట్'}, physiotherapist:{hi:'फिजियोथेरेपिस्ट',te:'ఫిజియోథెరపిస్ట్'}, 'dental-hygienist':{hi:'दंत स्वास्थ्य विशेषज्ञ',te:'దంత ఆరోగ్య నిపుణుడు'}, radiographer:{hi:'रेडियोग्राफर',te:'రేడియోగ్రాఫర్'}, paramedic:{hi:'आपात चिकित्सा सहायक',te:'అత్యవసర వైద్య సహాయకుడు'}, 'healthcare-assistant':{hi:'स्वास्थ्य सेवा सहायक / जीडीए',te:'ఆరోగ్య సంరక్షణ సహాయకుడు / జీడీఏ'}, 'medical-coder':{hi:'मेडिकल कोडर',te:'మెడికల్ కోడర్'}, veterinarian:{hi:'पशु चिकित्सक',te:'పశువైద్యుడు'},
  electrician:{hi:'बिजली मिस्त्री',te:'ఎలక్ట్రీషియన్'}, plumber:{hi:'प्लंबर',te:'ప్లంబర్'}, welder:{hi:'वेल्डर',te:'వెల్డర్'}, 'cnc-operator':{hi:'सीएनसी मशीन ऑपरेटर',te:'సీఎన్‌సీ యంత్ర నిర్వాహకుడు'}, 'solar-technician':{hi:'सौर पीवी तकनीशियन',te:'సౌర పీవీ సాంకేతిక నిపుణుడు'}, 'hvac-technician':{hi:'एचवीएसी तकनीशियन',te:'హెచ్‌వీఏసీ సాంకేతిక నిపుణుడు'}, 'automotive-mechanic':{hi:'वाहन मैकेनिक',te:'వాహన మెకానిక్'}, 'ev-technician':{hi:'इलेक्ट्रिक वाहन तकनीशियन',te:'విద్యుత్ వాహన సాంకేతిక నిపుణుడు'}, carpenter:{hi:'बढ़ई',te:'వడ్రంగి'}, mason:{hi:'राजमिस्त्री',te:'తాపీ మేస్త్రీ'}, tailor:{hi:'दर्जी / परिधान निर्माता',te:'దర్జీ / వస్త్ర తయారీదారు'}, beautician:{hi:'ब्यूटीशियन / कॉस्मेटोलॉजिस्ट',te:'బ్యూటీషియన్ / కాస్మెటాలజిస్ట్'}, chef:{hi:'शेफ / रसोइया',te:'షెఫ్ / వంట నిపుణుడు'}, 'security-guard':{hi:'सुरक्षा प्रहरी',te:'భద్రతా సిబ్బంది'}, 'mobile-repair-technician':{hi:'मोबाइल मरम्मत तकनीशियन',te:'మొబైల్ మరమ్మత్తు సాంకేతిక నిపుణుడు'},
  'chartered-accountant':{hi:'चार्टर्ड अकाउंटेंट',te:'చార్టర్డ్ అకౌంటెంట్'}, 'financial-analyst':{hi:'वित्तीय विश्लेषक',te:'ఆర్థిక విశ్లేషకుడు'}, 'loan-officer':{hi:'ऋण अधिकारी',te:'రుణ అధికారి'}, 'insurance-agent':{hi:'बीमा अभिकर्ता',te:'బీమా ప్రతినిధి'}, auditor:{hi:'लेखा परीक्षक',te:'ఆడిటర్'}, 'investment-advisor':{hi:'निवेश सलाहकार',te:'పెట్టుబడి సలహాదారు'}, accountant:{hi:'लेखाकार',te:'అకౌంటెంట్'}, 'data-entry-operator':{hi:'डेटा प्रविष्टि ऑपरेटर',te:'డేటా ఎంట్రీ ఆపరేటర్'},
  teacher:{hi:'विद्यालय शिक्षक',te:'పాఠశాల ఉపాధ్యాయుడు'}, 'corporate-trainer':{hi:'कॉर्पोरेट प्रशिक्षक',te:'కార్పొరేట్ శిక్షకుడు'}, 'career-counselor':{hi:'करियर परामर्शदाता',te:'కెరీర్ సలహాదారు'}, 'instructional-designer':{hi:'शिक्षण सामग्री डिज़ाइनर',te:'బోధనా రూపకర్త'},
  farmer:{hi:'किसान',te:'రైతు'}, 'agri-extension-worker':{hi:'कृषि प्रसार कार्यकर्ता',te:'వ్యవసాయ విస్తరణ కార్యకర్త'}, 'organic-farmer':{hi:'जैविक खेती विशेषज्ञ',te:'సేంద్రియ వ్యవసాయ నిపుణుడు'}, horticulturist:{hi:'बागवानी विशेषज्ञ',te:'ఉద్యానవన నిపుణుడు'}, 'dairy-farmer':{hi:'डेयरी किसान',te:'పాడి రైతు'}, 'poultry-farmer':{hi:'कुक्कुट पालक',te:'కోళ్ల పెంపక రైతు'}, 'aquaculture-specialist':{hi:'जलीय कृषि विशेषज्ञ',te:'జలకృషి నిపుణుడు'},
  'graphic-designer':{hi:'ग्राफ़िक डिज़ाइनर',te:'గ్రాఫిక్ డిజైనర్'}, 'video-editor':{hi:'वीडियो संपादक',te:'వీడియో ఎడిటర్'}, photographer:{hi:'फ़ोटोग्राफ़र',te:'ఫోటోగ్రాఫర్'}, 'content-writer':{hi:'सामग्री लेखक',te:'కంటెంట్ రచయిత'}, 'social-media-manager':{hi:'सोशल मीडिया प्रबंधक',te:'సోషల్ మీడియా మేనేజర్'}, animator:{hi:'एनिमेटर',te:'యానిమేటర్'}, 'music-producer':{hi:'संगीत निर्माता',te:'సంగీత నిర్మాత'}, 'interior-designer':{hi:'आंतरिक सज्जा डिज़ाइनर',te:'ఇంటీరియర్ డిజైనర్'},
  'warehouse-manager':{hi:'गोदाम प्रबंधक',te:'గిడ్డంగి మేనేజర్'}, 'supply-chain-analyst':{hi:'आपूर्ति शृंखला विश्लेषक',te:'సరఫరా గొలుసు విశ్లేషకుడు'}, 'logistics-coordinator':{hi:'लॉजिस्टिक्स समन्वयक',te:'లాజిస్టిక్స్ సమన్వయకర్త'}, 'store-manager':{hi:'स्टोर प्रबंधक',te:'స్టోర్ మేనేజర్'}, 'retail-sales-associate':{hi:'खुदरा बिक्री सहयोगी',te:'రిటైల్ విక్రయ సహాయకుడు'}, 'visual-merchandiser':{hi:'विज़ुअल मर्चेंडाइज़र',te:'విజువల్ మర్చండైజర్'}, 'ecommerce-manager':{hi:'ई-कॉमर्स प्रबंधक',te:'ఈ-కామర్స్ మేనేజర్'}, 'customer-service-rep':{hi:'ग्राहक सेवा प्रतिनिधि',te:'వినియోగదారుల సేవా ప్రతినిధి'},
  'environmental-consultant':{hi:'पर्यावरण सलाहकार',te:'పర్యావరణ సలహాదారు'}, 'waste-management-specialist':{hi:'अपशिष्ट प्रबंधन विशेषज्ञ',te:'వ్యర్థ నిర్వహణ నిపుణుడు'}, 'renewable-energy-technician':{hi:'नवीकरणीय ऊर्जा तकनीशियन',te:'పునరుత్పాదక ఇంధన సాంకేతిక నిపుణుడు'}, 'sustainability-manager':{hi:'सततता प्रबंधक',te:'సుస్థిరత మేనేజర్'}, 'gis-specialist':{hi:'जीआईएस विशेषज्ञ',te:'జీఐఎస్ నిపుణుడు'}, 'water-resource-specialist':{hi:'जल संसाधन विशेषज्ञ',te:'జల వనరుల నిపుణుడు'},
  'civil-servant':{hi:'सिविल सेवक / आईएएस अधिकारी',te:'సివిల్ సర్వెంట్ / ఐఏఎస్ అధికారి'}, 'policy-analyst':{hi:'नीति विश्लेषक',te:'విధాన విశ్లేషకుడు'}, 'ngo-program-manager':{hi:'गैर-सरकारी कार्यक्रम प्रबंधक',te:'ఎన్‌జీఓ కార్యక్రమ మేనేజర్'}, 'social-worker':{hi:'सामाजिक कार्यकर्ता',te:'సామాజిక కార్యకర్త'}, 'public-relations-officer':{hi:'जनसंपर्क अधिकारी',te:'ప్రజా సంబంధాల అధికారి'},
  'quality-inspector':{hi:'गुणवत्ता आश्वासन निरीक्षक',te:'నాణ్యత హామీ పరిశీలకుడు'}, 'production-supervisor':{hi:'उत्पादन पर्यवेक्षक',te:'ఉత్పత్తి పర్యవేక్షకుడు'}, 'cnc-programmer':{hi:'सीएनसी प्रोग्रामर',te:'సీఎన్‌సీ ప్రోగ్రామర్'}, 'industrial-engineer':{hi:'औद्योगिक इंजीनियर',te:'పారిశ్రామిక ఇంజనీర్'}, journalist:{hi:'पत्रकार',te:'పాత్రికేయుడు'}, 'digital-marketer':{hi:'डिजिटल विपणन विशेषज्ञ',te:'డిజిటల్ మార్కెటింగ్ నిపుణుడు'}, 'hr-manager':{hi:'मानव संसाधन प्रबंधक',te:'మానవ వనరుల మేనేజర్'}, 'business-analyst':{hi:'व्यवसाय विश्लेषक',te:'వ్యాపార విశ్లేషకుడు'}, 'project-manager':{hi:'परियोजना प्रबंधक',te:'ప్రాజెక్ట్ మేనేజర్'}, 'legal-assistant':{hi:'कानूनी सहायक / पैरालीगल',te:'న్యాయ సహాయకుడు / పారాలీగల్'}, lawyer:{hi:'वकील / अधिवक्ता',te:'న్యాయవాది'}, 'real-estate-agent':{hi:'अचल संपत्ति अभिकर्ता',te:'స్థిరాస్తి ప్రతినిధి'},
  'blockchain-developer':{hi:'ब्लॉकचेन डेवलपर',te:'బ్లాక్‌చెయిన్ డెవలపర్'}, 'drone-pilot':{hi:'ड्रोन ऑपरेटर / पायलट',te:'డ్రోన్ ఆపరేటర్ / పైలట్'}, 'robotics-engineer':{hi:'रोबोटिक्स इंजीनियर',te:'రోబోటిక్స్ ఇంజనీర్'}, 'iot-specialist':{hi:'आईओटी विशेषज्ञ',te:'ఐఓటీ నిపుణుడు'}, '3d-printing-technician':{hi:'3डी प्रिंटिंग तकनीशियन',te:'3డీ ప్రింటింగ్ సాంకేతిక నిపుణుడు'},
};

export function occupationName(id: string, english: string, lang: Language, bilingual = true): string {
  if (lang === 'en') return english;
  const localized = names[id]?.[lang];
  if (!localized) return english;
  return bilingual ? `${english} · ${localized}` : localized;
}

export function occupationTranslationCoverage(ids: string[]): string[] {
  return ids.filter(id => !names[id]);
}
