import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const preflight = readFileSync('scripts/hosted-sih-preflight.ts', 'utf8');
const fixture = readFileSync('scripts/hosted-sih-fixture.ts', 'utf8');
const smoke = readFileSync('scripts/hosted-sih-smoke.ts', 'utf8');
const deployment = readFileSync('scripts/cloudflare-deploy.ts', 'utf8');
const migrationAudit = readFileSync('scripts/hosted-migration-audit.ts', 'utf8');
const runbook = readFileSync('docs/sih26044-hosted-validation-runbook.md', 'utf8');
assert.match(preflight, /mmwgnsggnllwgshipnwh/);
assert.match(preflight, /READ_ONLY_PREFLIGHT/);
assert.match(preflight, /migration-list/);
assert.match(fixture, /CREATE_CONTROLLED_SIH_FIXTURES/);
assert.match(fixture, /example\.invalid/);
assert.match(fixture, /SUSPEND_CONTROLLED_SIH_FIXTURES/);
assert.match(fixture, /organization_membership_roles/);
assert.match(fixture, /app_metadata/);
assert.match(fixture, /Refusing to repurpose existing Auth user/);
assert.match(fixture, /kind: 'government'/);
assert.match(fixture, /slug: 'policy-analyst'[\s\S]{0,160}orgId: ids\.governmentA[\s\S]{0,160}role: 'policy_program_analyst'/);
assert.doesNotMatch(fixture, /VITE_/);
assert.match(smoke, /recruiter-b/);
assert.match(smoke, /record_authoritative_audit/);
assert.match(deployment, /DEPLOY_SIH26044_PRODUCTION/);
assert.match(deployment, /--strict/);
assert.match(migrationAudit, /supabase_migrations\.schema_migrations/);
assert.match(migrationAudit, /semanticallyMissing/);
assert.match(runbook, /SUPABASE_ACCESS_TOKEN/);
assert.match(runbook, /Never reset/);
const missingCredentials = spawnSync('npx', ['tsx', 'scripts/hosted-sih-preflight.ts'], { encoding: 'utf8', env: { PATH: process.env.PATH ?? '' } });
assert.notEqual(missingCredentials.status, 0);
assert.match(`${missingCredentials.stdout}${missingCredentials.stderr}`, /SIH_SUPABASE_URL is required/);
console.log('Hosted validation readiness QA passed: 21 assertions');
